spring.application.name=creditInformation
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_card_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#email sender config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rum2night@gmail.com
spring.mail.password=itxe poah pprm inmu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.admin.verification.code=9210



