spring.application.name=creditInformation


#email sender config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rum2night@gmail.com
spring.mail.password=itxe poah pprm inmu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.admin.verification.code=9210

spring.profiles.active=dev

#server local
server.address=0.0.0.0
server.port=8080



